### ISSUE TITLE
Create a NavBar component.

### ISSUE THREAD

**Issue by StoicNeutron** [StoicNeutron/GMU_ACM#12]
Create a Navigation Bar component (recommend library Mantine) according to the project prototype which you can find within the readme file. 

Acceptance criteria:
The NavBar component is render without error and produce a correct navbar as in the prototype picture.
The NavBar can accept a prop string, ex: <NavBar 'Home' /> , <NavBar 'About' /> so that we can reuse this in both pages.

Answer Question Please Ask!

**Comment by ppongpeauk** [comment]
Does the Nav component need to change when navigating between the two pages, home and about?

**Comment by StoicNeutron** [comment]
We already have two separate pages /home and /about. So, in this case, when users click on home, it redirect to the /home page and vice versa. Just my idea, if you have a better idea, you can suggest.

**Comment by ppongpeauk** [comment]
I don't think having a dedicated prop is necessary for that! Looking at the schematics in README.md, the Nav component seems to appear the same between both pages.
