### ISSUE TITLE
Create /home main layout

### ISSUE THREAD

**Issue by StoicNeutron** [StoicNeutron/GMU_ACM#17]
Base on the /home prototype. Create a main layout components, within this main layout component it contains 2 child components one call Visualizer and the other one call controller component. 
Main Layout Component (Parent):
Span 100% width of the screen, Height: to be decide by the dev as seem fit.
Visualizer Component (Child) on the right& Controller Component (Child) on the left:
Set inside the Main Layout Component, each share the space available within the Main Layout Component equally.

Acceptance Criteria:
To be review and approve by all project_lead.

**Comment by ppongpeauk** [comment]
Did you mean to say that the visualizer component should be on the left and the controller component should be on the right, or is the diagram provided in README.md outdated?

**Comment by StoicNeutron** [comment]
Oh, you are right. My mistake!

**Comment by StoicNeutron** [comment]
close #17
