### ISSUE TITLE
Webapp: Change the App Favicon.

### ISSUE THREAD

**Issue by StoicNeutron** [StoicNeutron/GMU_ACM#3]
Update the current app favicon to the attached favicon.
[favicon.ico.zip](https://github.com/StoicNeutron/GMU_ACM/files/14171131/favicon.ico.zip)

Acceptance Criteria:
The webapp favicon icon is update to the new attached favicon file.

**Comment by StoicNeutron** [comment]
This issue is still not resolve yet. Reopen.

**Comment by Natasha-Zero** [comment]
I'll do this.

**Comment by Natasha-Zero** [comment]
I ran npm run dev, but the favicon is already there.

**Comment by StoicNeutron** [comment]
Ok, I see. Thank u tho.
