### ISSUE TITLE
Mantine Button Issue

### ISSUE THREAD

**Issue by StoicNeutron** [StoicNeutron/GMU_ACM#38]
Currently there are two Button Components from Mantine Library use within the Controller.tsx file. For some reason, the Buttons don't show any color or txt color. 

Acceptance criteria:
There are 2 visible buttons under the select drop down speed button.

**Comment by ppongpeauk** [comment]
The problem seems to go away when you remove `import "@/styles/globals.css";` from _app.tsx.

**Comment by StoicNeutron** [comment]
Nice!, Let me try.
