### ISSUE TITLE
Restore Style relate to issue #38

### ISSUE THREAD

**Issue by StoicNeutron** [StoicNeutron/GMU_ACM#42]
After bug #38 resolved, the style that related were damage by this. Thus restore the style back to the prior resolved issue.

**Comment by AMATAKYVI** [comment]
The bug already fixed?

**Comment by StoicNeutron** [comment]
Yes, correct. The bug was already resolved. U can take a look at https://github.com/StoicNeutron/GMU_ACM/issues/38
